### ISSUE TITLE
Inversion of multiple dispersion curves

### ISSUE THREAD

**Issue by jaisinghverma** [jpvantassel/swbatch#5]
Hello.
Using the code, the inversion can be carried out for a single dispersion curve. However, if there are a number of dispersion curves, such as 250 dispersion curves obtained considering the uncertainty consistent Vs profiles (Vantassel & Cox, 2021), how can the inversion be done simultaneously?

**Comment by jpvantassel** [comment]
@jaisinghverma,
All you need to do is provide multiple *.target files.
